### ISSUE TITLE
友链和相册页面报错

### ISSUE THREAD

**Issue by domye** [lh1me/hexo-theme-aomori#106]
Unhandled rejection TypeError: D:\a\themes\aomori\layout\page.ejs:11
    9|
    10| <div class="<%= page.layout %>">
 >> 11|   <%- partial(`_partial/page/${page.layout}`, {post: page, index: false}) %>
    12| </div>
    13|
    14| <% } else { %>

D:\a\themes\aomori\layout\_partial\page\photography.ejs:3
    1| <div class="columns clearfix">
    2|         <div class="column col-md-12">
 >> 3|             <% site.data.photography.forEach(function(item, index){ %>
    4|                 <% if (((index) % 3) === 0) { %>
    5|                     <%- partial('photography-item', {item}) %>
    6|                 <% } %>

Cannot read properties of undefined (reading 'forEach')
    at eval ("D:\\a\\themes\\aomori\\layout\\_partial\\page\\photography.ejs":12:30)
    at photography (D:\a\node_modules\_ejs@3.1.8@ejs\lib\ejs.js:703:17)
    at _View._compiledSync (D:\a\node_modules\_hexo@6.2.0@hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\a\node_modules\_hexo@6.2.0@hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\a\node_modules\_hexo@6.2.0@hexo\lib\plugins\helper\partial.js:34:15)
    at eval ("D:\\a\\themes\\aomori\\layout\\page.ejs":27:17)
    at page (D:\a\node_modules\_ejs@3.1.8@ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\a\node_modules\_hexo@6.2.0@hexo\lib\theme\view.js:136:50)
    at _View.render (D:\a\node_modules\_hexo@6.2.0@hexo\lib\theme\view.js:39:17)
    at D:\a\node_modules\_hexo@6.2.0@hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\a\node_modules\_bluebird@3.7.2@bluebird\js\release\util.js:16:23)
    at D:\a\node_modules\_bluebird@3.7.2@bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\a\node_modules\_hexo@6.2.0@hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:987:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Unhandled rejection TypeError: D:\a\themes\aomori\layout\page.ejs:5
    3|
    4| <div class="<%= page.layout %>">
 >> 5|   <%- partial(`_partial/page/${page.layout}`, {post: page, index: false}) %>
    6| </div>
    7|
    8| <% } else if (page.layout === 'photography') { %>

D:\a\themes\aomori\layout\_partial\page\friends.ejs:1
 >> 1| <% site.data.friends.forEach((items) => { %>
    2|     <div class="friends-category">
    3|         <div class="friends-category-title">
    4|             <%= items.category %>

Cannot read properties of undefined (reading 'forEach')
    at eval ("D:\\a\\themes\\aomori\\layout\\_partial\\page\\friends.ejs":10:26)
    at friends (D:\a\node_modules\_ejs@3.1.8@ejs\lib\ejs.js:703:17)
    at _View._compiledSync (D:\a\node_modules\_hexo@6.2.0@hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\a\node_modules\_hexo@6.2.0@hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\a\node_modules\_hexo@6.2.0@hexo\lib\plugins\helper\partial.js:34:15)
    at eval ("D:\\a\\themes\\aomori\\layout\\page.ejs":18:17)
    at page (D:\a\node_modules\_ejs@3.1.8@ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\a\node_modules\_hexo@6.2.0@hexo\lib\theme\view.js:136:50)
    at _View.render (D:\a\node_modules\_hexo@6.2.0@hexo\lib\theme\view.js:39:17)
    at D:\a\node_modules\_hexo@6.2.0@hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\a\node_modules\_bluebird@3.7.2@bluebird\js\release\util.js:16:23)
    at D:\a\node_modules\_bluebird@3.7.2@bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\a\node_modules\_hexo@6.2.0@hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:987:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by lh1me** [comment]
你的配置错了，导致读取不到数据
