### ISSUE TITLE
第一次安装主题报错

### ISSUE THREAD

**Issue by forliuyifei** [lh1me/hexo-theme-aomori#30]
默认的主题没问题。使用这个主题的时候，生成的index.html都是空的。
```
ERROR {
  err: TypeError: /data/data/com.termux/files/home/copy.loafing.cn/themes/hexo-theme-aomori/layout/layout.ejs:20
      18|             <aside class="sidebar">
      19|             <% } %>
   >> 20|                 <%- partial('_partial/sidebar') %>
      21|             </aside>
      22|         </div>
      23|     </div>

  /data/data/com.termux/files/home/copy.loafing.cn/themes/hexo-theme-aomori/layout/_partial/sidebar.ejs:7
      5|
      6| <div class="widget" id="widget">
   >> 7|     <% config.aomori_widgets.forEach(function(widget){ %>
      8|       <%- partial('_widget/' + widget) %>
      9|     <% }) %>
      10| </div>

  Cannot read property 'forEach' of undefined
      at eval (/data/data/com.termux/files/home/copy.loafing.cn/themes/hexo-theme-aomori/layout/_partial/sidebar.ejs:19:30)
      at sidebar (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/ejs/lib/ejs.js:682:17)
      at _View._compiledSync (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/hexo/lib/theme/view.js:132:24)
      at _View.renderSync (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/hexo/lib/theme/view.js:59:25)
      at Object.partial (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
      at eval (/data/data/com.termux/files/home/copy.loafing.cn/themes/hexo-theme-aomori/layout/layout.ejs:26:17)
      at layout (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/ejs/lib/ejs.js:682:17)
      at _View._compiled (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/hexo/lib/theme/view.js:136:50)
      at _View.render (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/hexo/lib/theme/view.js:39:17)
      at /data/data/com.termux/files/home/copy.loafing.cn/node_modules/hexo/lib/theme/view.js:51:25
      at tryCatcher (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21) {
    path: '/data/data/com.termux/files/home/copy.loafing.cn/themes/hexo-theme-aomori/layout/layout.ejs'
  }
} Render HTML failed: index.html
Unhandled rejection TypeError: /data/data/com.termux/files/home/copy.loafing.cn/themes/hexo-theme-aomori/layout/layout.ejs:20
    18|             <aside class="sidebar">
    19|             <% } %>
 >> 20|                 <%- partial('_partial/sidebar') %>
    21|             </aside>
    22|         </div>
    23|     </div>

/data/data/com.termux/files/home/copy.loafing.cn/themes/hexo-theme-aomori/layout/_partial/sidebar.ejs:7
    5|
    6| <div class="widget" id="widget">
 >> 7|     <% config.aomori_widgets.forEach(function(widget){ %>
    8|       <%- partial('_widget/' + widget) %>
    9|     <% }) %>
    10| </div>

Cannot read property 'forEach' of undefined
    at eval (/data/data/com.termux/files/home/copy.loafing.cn/themes/hexo-theme-aomori/layout/_partial/sidebar.ejs:19:30)
    at sidebar (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiledSync (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (/data/data/com.termux/files/home/copy.loafing.cn/themes/hexo-theme-aomori/layout/layout.ejs:26:17)
    at layout (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/hexo/lib/theme/view.js:39:17)
    at /data/data/com.termux/files/home/copy.loafing.cn/node_modules/hexo/lib/theme/view.js:51:25
    at tryCatcher (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/data/data/com.termux/files/home/copy.loafing.cn/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```

**Comment by forliuyifei** [comment]
明白了是解压主题文件夹的时候多了一层目录，没注意😭
