### ISSUE TITLE
hexo s之后在页面请求出现报错

### ISSUE THREAD

**Issue by prkom** [lh1me/hexo-theme-aomori#36]
报错信息如下
```
INFO  Validating config
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
ERROR {
  err: TypeError: /hexo/themes/hexo-theme-aomori/layout/layout.ejs:20
      18|             <aside class="sidebar">
      19|             <% } %>
   >> 20|                 <%- partial('_partial/sidebar') %>
      21|             </aside>
      22|         </div>
      23|     </div>
  
  /hexo/themes/hexo-theme-aomori/layout/_partial/sidebar.ejs:7
      5| 
      6| <div class="widget" id="widget">
   >> 7|     <% config.aomori_widgets.forEach(function(widget){ %>
      8|       <%- partial('_widget/' + widget) %>
      9|     <% }) %>
      10| </div>
  
  Cannot read property 'forEach' of undefined
      at eval (/hexo/themes/hexo-theme-aomori/layout/_partial/sidebar.ejs:21:30)
      at sidebar (/hexo/node_modules/ejs/lib/ejs.js:682:17)
      at _View._compiledSync (/hexo/node_modules/hexo/lib/theme/view.js:132:24)
      at _View.renderSync (/hexo/node_modules/hexo/lib/theme/view.js:59:25)
      at Object.partial (/hexo/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
      at eval (/hexo/themes/hexo-theme-aomori/layout/layout.ejs:28:17)
      at layout (/hexo/node_modules/ejs/lib/ejs.js:682:17)
      at _View._compiled (/hexo/node_modules/hexo/lib/theme/view.js:136:50)
      at _View.render (/hexo/node_modules/hexo/lib/theme/view.js:39:17)
      at /hexo/node_modules/hexo/lib/theme/view.js:51:25
      at tryCatcher (/hexo/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/hexo/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/hexo/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/hexo/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/hexo/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/hexo/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/hexo/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/hexo/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/hexo/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (node:internal/timers:463:21) {
    path: '/hexo/themes/hexo-theme-aomori/layout/layout.ejs'
  }
} Render HTML failed: index.html
Unhandled rejection TypeError: /hexo/themes/hexo-theme-aomori/layout/layout.ejs:20
    18|             <aside class="sidebar">
    19|             <% } %>
 >> 20|                 <%- partial('_partial/sidebar') %>
    21|             </aside>
    22|         </div>
    23|     </div>

/hexo/themes/hexo-theme-aomori/layout/_partial/sidebar.ejs:7
    5| 
    6| <div class="widget" id="widget">
 >> 7|     <% config.aomori_widgets.forEach(function(widget){ %>
    8|       <%- partial('_widget/' + widget) %>
    9|     <% }) %>
    10| </div>

Cannot read property 'forEach' of undefined
    at eval (/hexo/themes/hexo-theme-aomori/layout/_partial/sidebar.ejs:21:30)
    at sidebar (/hexo/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiledSync (/hexo/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/hexo/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/hexo/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (/hexo/themes/hexo-theme-aomori/layout/layout.ejs:28:17)
    at layout (/hexo/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/hexo/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/hexo/node_modules/hexo/lib/theme/view.js:39:17)
    at /hexo/node_modules/hexo/lib/theme/view.js:51:25
    at tryCatcher (/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/hexo/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/hexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/hexo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/hexo/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/hexo/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/hexo/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/hexo/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/hexo/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:463:21)


```

软件版本：
```
INFO  Validating config
hexo: 5.2.0
hexo-cli: 4.2.0
os: Darwin 19.6.0 darwin x64
node: 15.3.0
v8: 8.6.395.17-node.22
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.16.1
modules: 88
nghttp2: 1.41.0
napi: 7
llhttp: 2.1.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
```

主题很好看，但是安装过程出现了问题，google 找不到相关解决办法，希望可以告知怎么解决。

**Comment by lh1me** [comment]
**aomori_widgets** 这个配置项没有配

**Comment by prkom** [comment]
感谢
