### ISSUE TITLE
  Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by JyHu** [lh1me/hexo-theme-aomori#43]
```
INFO  Validating config
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
ERROR {
  err: TypeError: /Users/jo/Documents/Hexo/JosApp/themes/hexo-theme-aomori/layout/layout.ejs:20
      18|             <aside class="sidebar">
      19|             <% } %>
   >> 20|                 <%- partial('_partial/sidebar') %>
      21|             </aside>
      22|         </div>
      23|     </div>
  
  /Users/jo/Documents/Hexo/JosApp/themes/hexo-theme-aomori/layout/_partial/sidebar.ejs:7
      5| 
      6| <div class="widget" id="widget">
   >> 7|     <% config.aomori_widgets.forEach(function(widget){ %>
      8|       <%- partial('_widget/' + widget) %>
      9|     <% }) %>
      10| </div>
  
  Cannot read property 'forEach' of undefined
      at eval (/Users/jo/Documents/Hexo/JosApp/themes/hexo-theme-aomori/layout/_partial/sidebar.ejs:21:30)
      at sidebar (/Users/jo/Documents/Hexo/JosApp/node_modules/ejs/lib/ejs.js:682:17)
      at _View._compiledSync (/Users/jo/Documents/Hexo/JosApp/node_modules/hexo/lib/theme/view.js:132:24)
      at _View.renderSync (/Users/jo/Documents/Hexo/JosApp/node_modules/hexo/lib/theme/view.js:59:25)
      at Object.partial (/Users/jo/Documents/Hexo/JosApp/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
      at eval (/Users/jo/Documents/Hexo/JosApp/themes/hexo-theme-aomori/layout/layout.ejs:28:17)
      at layout (/Users/jo/Documents/Hexo/JosApp/node_modules/ejs/lib/ejs.js:682:17)
      at _View._compiled (/Users/jo/Documents/Hexo/JosApp/node_modules/hexo/lib/theme/view.js:136:50)
      at _View.render (/Users/jo/Documents/Hexo/JosApp/node_modules/hexo/lib/theme/view.js:39:17)
      at /Users/jo/Documents/Hexo/JosApp/node_modules/hexo/lib/theme/view.js:51:25
      at tryCatcher (/Users/jo/Documents/Hexo/JosApp/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/jo/Documents/Hexo/JosApp/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/jo/Documents/Hexo/JosApp/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/jo/Documents/Hexo/JosApp/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/jo/Documents/Hexo/JosApp/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/jo/Documents/Hexo/JosApp/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/jo/Documents/Hexo/JosApp/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/jo/Documents/Hexo/JosApp/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/jo/Documents/Hexo/JosApp/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (node:internal/timers:464:21) {
    path: '/Users/jo/Documents/Hexo/JosApp/themes/hexo-theme-aomori/layout/layout.ejs'
  }
} Render HTML failed: index.html
```

**Comment by spiderman-spiderman** [comment]
aomori_widgets:
  - toc # Article navigation
  - category  # Article classification
  - tag # Article tags
  - recent_posts  # latest articles
  - archive # Article Archive

  aomori_widgets:应该是没有配置

**Comment by endll** [comment]
> aomori_widgets:
> 
> * toc # Article navigation
> * category  # Article classification
> * tag # Article tags
> * recent_posts  # latest articles
> * archive # Article Archive
> 
> aomori_widgets:应该是没有配置

正好我也是这个问题，确实，在全局_config下配置aomori_widgets 就可以了，感谢！

**Comment by lh1me** [comment]
**v1.19.0** 优化这个问题了，**aomori_widgets** 增加了默认配置。

**Comment by JyHu** [comment]
> **v1.19.0** 优化这个问题了，**aomori_widgets** 增加了默认配置。

感谢提供好看的模版资源

**Comment by JyHu** [comment]
```
aomori_menu:
  Home: /
  Archives: /archive
  Tags: /tag
```

添加了menu后但无法显示，怎么办啊？
